CREATE TABLE tableName 
(
    ID	INT,
    QuestionTitle	VARCHAR(512),
    Type	VARCHAR(512),
    QuestionAnswer	VARCHAR(512),
    CourseID	VARCHAR(512)
);

INSERT INTO tableName (ID, QuestionTitle, Type, QuestionAnswer, CourseID) VALUES
	('1', 'What is HTML?', 'MCQ ', 'd', '1'),
	('2', 'Who is the father of HTML?', 'MCQ ', 'b', '1'),
	('3', 'HTML stands for __________', 'MCQ ', 'a', '1'),
	('4', ' What is the correct syntax of doctype in HTML5?', 'MCQ ', 'd', '1'),
	('5', 'Which of the following is used to read an HTML page and render it?', 'MCQ ', 'c', '1'),
	('6', 'Which of the following tag is used for inserting the largest heading in HTML?', 'MCQ ', 'b', '1'),
	('7', ' What is DOM in HTML?', 'MCQ ', 'd', '1'),
	('8', ' In which part of the HTML metadata is contained?', 'MCQ ', 'a', '1'),
	('9', 'Which element is used to get highlighted text in HTML5?', 'MCQ ', 'b', '1'),
	('10', 'Which of the following is not a HTML5 tag?', 'MCQ ', 'c', '1'),
	('11', 'we write comments in HTML [<!……>]', 'True & False ', 't', '1'),
	('12', 'In HTML5 defines video or movie content <movie>', 'True & False ', 'f', '1'),
	('13', ' the element color is associated with the HTML table layout?', 'True & False ', 'f', '1'),
	('14', 'CSS is used for or styling HTML5 layout', 'True & False ', 't', '1'),
	('15', 'HTML tag is used to insert an image is <img src=”htmllogo.jpg” />', 'True & False ', 't', '1'),
	('16', 'HTML is a subset of SGML', 'True & False ', 't', '1'),
	('17', 'character [\] is used to represent when a tag is closed in HTML', 'True & False ', 'f', '1'),
	('18', 'The HTML paragraph tag is <p>', 'True & False ', 't', '1'),
	('19', 'HTML element is used for short quote is <q>', 'True & False ', 't', '1'),
	('20', 'HTML tag is used to create an unordered list is  <lu>', 'True & False ', 'f', '1'),
	('21', 'Which of the following tag is used to embed css in html page', 'MCQ', 'd', '2'),
	('22', 'Which of the following CSS selectors are used to specify a group of elements', 'MCQ', 'c', '2'),
	('23', 'Which of the following has introduced text, list, box, margin, border, color, and background properties', 'MCQ', 'c', '2'),
	('24', 'Which of the following CSS framework is used to create a responsive design', 'MCQ', 'd', '2'),
	('25', 'Which of the following CSS selector is used to specify a rule to bind a particular unique element', 'MCQ', 'b', '2'),
	('26', 'Which of the following type of HTML tag is used to define an internal style sheet', 'MCQ', 'd', '2'),
	('27', 'Which of the following CSS property is used to make the text bold', 'MCQ', 'b', '2'),
	('28', 'Which of the following CSS style property is used to specify an italic text', 'MCQ', 'c', '2'),
	('29', 'Which of the following are the CSS Extension Prefixes for Webkit', 'MCQ', 'd', '2'),
	('30', 'Which of the following CSS property sets the font size of text', 'MCQ', 'a', '2'),
	('31', 'the <style> tag is used to embed css in html page', 'True & False', 't', '2'),
	('32', 'Id CSS selectors are used to specify a group of elements', 'True & False', 'f', '2'),
	('33', 'CSS has introduced text, list, box, margin, border, color, and background properties', 'True & False', 't', '2'),
	('34', 'Rails CSS framework is used to create a responsive design', 'True & False', 'f', '2'),
	('35', 'Class CSS selector is used to specify a rule to bind a particular unique element', 'True & False', 'f', '2'),
	('36', '<Style> type of HTML tag is used to define an internal style sheet', 'True & False', 't', '2'),
	('37', 'font-weight CSS property is used to make the text bold', 'True & False', 't', '2'),
	('38', 'font-style CSS style property is used to specify an italic text', 'True & False', 't', '2'),
	('39', 'web are the CSS Extension Prefixes for Webkit', 'True & False', 'f', '2'),
	('40', 'font-size CSS property sets the font size of text', 'True & False', 't', '2'),
	('41', 'Which type of JavaScript language is', 'MCQ', 'b', '3'),
	('42', 'Which one of the following also known as Conditional Expression', 'MCQ', 'd', '3'),
	('43', 'When interpreter encounters an empty statements, what it will do', 'MCQ', 'd', '3'),
	('44', '"The ""function"" and "" var"" are known as"', 'MCQ', 'c', '3'),
	('45', 'Which of the following variables takes precedence over the others if the names are the same', 'MCQ', 'b', '3'),
	('46', 'Which one of the following is the correct way for calling the JavaScript code', 'MCQ', 'd', '3'),
	('47', 'Which of the following type of a variable is volatile', 'MCQ', 'a', '3'),
	('48', 'Which of the following option is used as hexadecimal literal beginning', 'MCQ', 'd', '3'),
	('49', 'In the JavaScript, which one of the following is not considered as an error:c', 'MCQ', 'c', '3'),
	('50', 'Which of the following number object function returns the value of the number?', 'MCQ', 'b', '3'),
	('51', 'The ability to combine embedded JavaScript code and JavaScript source files in a single web page is advantageous if you have multiple web pages.', 'True & False ', 't', '3'),
	('52', 'You can use a text string as a literal value or assign it to a variable.', 'True & False ', 't', '3'),
	('53', 'Assignment operators are used to perform mathematical calculations, such as addition, subtraction, multiplication, and division.', 'True & False ', 'f', '3'),
	('54', 'In an infinite loop, a loop statement never ends because its conditional expression is never truthy.', 'True & False ', 'f', '3'),
	('55', 'Web page authoring refers to the visual design and creation of the documents that appear on the World Wide Web.', 'True & False ', 'f', '3'),
	('56', '"The statement document.write(""This is a text string.""); prints ""This is a text string""."', 'True & False ', 'f', '3'),
	('57', 'Many apps installed on smartphones and tablets are technically web documents that access web servers.', 'True & False ', 't', '3'),
	('58', 'JavaScript can be used to delete persistent cookies in a program.', 'True & False ', 't', '3'),
	('59', 'A function must return a value.', 'True & False ', 'f ', '3'),
	('60', 'To round a number to the next highest integer you will use the round(x) Math class method.', 'True & False ', 'f', '3');